repos:
-   repo: local
    hooks:
    -   id: pio-test
        name: pio-test
        entry: pio test -e native -e nano33ble-renode --without-uploading
        pass_filenames: false
        language: system
        stages: [push]
